### PR TITLE
Add new contrasted color icons.

### PR DESCRIPTION
**Pull request by LazaroOnline**
Related to this issue:

https://github.com/GitTools/GitVersion/issues/2508

### CODE REVIEW

**Comment by arturcic** [comment]
@LazaroOnline could we change a little bit the GitVersion logo by removing the interior white color and only highlight the frame?
https://github.com/GitTools/graphics/blob/29a02ebc7cf795cd6a03e5282eb627a3e0668f34/GitVersion/Color/icon_128x128.png

**Comment by LazaroOnline** [comment]
I would prefer to keep the white interior in the tree to remove edge complexity and prevent jagged edges at small scales.
Here is a comparison example of how it would be seen from visual studio:
icon-compare_32

**Comment by arturcic** [comment]
Ok then agree.

**Comment by LazaroOnline** [comment]
whops, I forgot to update the icon in the README.md

**Comment by arturcic** [comment]
Ok merging this, would you mind updating the assets in the GitTools/GitVersion and GitTools/actions repo as well?
https://github.com/GitTools/GitVersion/tree/master/docs/input/docs/img
https://github.com/GitTools/GitVersion/blob/master/build/nuspec/GitVersion.Portable.nuspec
https://github.com/GitTools/actions/blob/master/docs/icon.png
https://github.com/GitTools/actions/blob/master/dist/azure/images/icon.png

**Pull request merged**
