### PR TITLE
New `ico` icons, and docs on creating them.

### PR DESCRIPTION
**Pull request by AdmiringWorm**
I added the gimp project files as well in this pr, as it allows for
easier updates if decided to include additional sizes in the `.ico` files
in the future.

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
The images in the documentation don't work, because the images are not in the `GitTools/graphics` repository.

The see the docs fully, navigate to: https://github.com/AdmiringWorm/graphics/blob/new-icos/docs/creating-ico-files.md

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@AdmiringWorm this is amazing, thank you for taking the time to do this!

**Comment by AdmiringWorm** [comment]
> LGTM!

Really 😕, no typos. That must be a first 😄 

> @AdmiringWorm this is amazing, thank you for taking the time to do this!

Not a problem. Worst of it was to create the docs for creating the icons.

**Comment by gep13** [comment]
Documentation is always great fun to do! `</sarcasm>`

**Pull request merged**
