### PR TITLE
(style) update grm icons to git stylized version

### PR DESCRIPTION
**Pull request by AdmiringWorm**
This changes the current icon with a git stylized
version of the GRM icon (redish background with black foreground).

/CC @gep13

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
Also added an `.ico` icon with the following sizes: `16x16`, `32x32`, `64x64`, `128x128` and `256x256`.
Think this could be beneficial as now the .NET Framework version of GRM can use an application icon.

Ran a quick test to see if it worked or not:

GRMIcon

**Comment by arturcic** [comment]
@AdmiringWorm can you share which tool have you used to generate the icon/png from svg? I would also want to do that for GitVersion

**Comment by AdmiringWorm** [comment]
@arturcic I just used [gimp](https://www.gimp.org/).

Just open the svg in the program, select the size you want and export it as a png.

**Comment by arturcic** [comment]
Got you, thanks

**Comment by AdmiringWorm** [comment]
Creating the icon (.ico) is a little more complicated in gimp though, if you are interested in creating one for that.
Would need to import the svg, duplicate the layer for each size you want, resize each layer, then export it as an `.ico`.

**Review by gep13 — APPROVED** [review]
LGTM!

**Pull request merged**
